ClaraSantosmf/FATEC-API-1-SEMESTRE

front/gerenciamento_turmas.html, regra_de_negocio/gerenciador_turmas.py, urls.py, views/funcoes_request_response.py
=> Adiciona a remoção de turmas por id. #26

dados/grupos.json, dados/turmas.json, front/gerenciamento_turmas.html, front/style/gerenciamento_turmas.css, urls.py
Fiz pequenas alterações no css que otimizaram o espaço de tela e resolvi o conflito no url.py
=> Resolvendo conflitos

front/listar_grupo.html, front/style/gerenciamento_grupos.css, regra_de_negocio/gerenciador_grupos.py, regra_de_negocio/gerenciador_turmas.py, regra_de_negocio/service.py, urls.py, views/funcoes_request_response.py
Backend e fronted da issue listar_grupo
#29
=> Sara/listar grupo #29

dados/notas.json, front/gerenciamento_turmas.html, front/global_settings.html, front/index.html, front/listar_grupo.html, front/scripts/index_script.js, front/style/custom.css, front/style/gerenciamento_turmas.css
Tirei os links em excesso e fiz o logo aparecer na tela no tamanho ideal.
=> Ruth/dt padronizar logo#110

regra_de_negocio/gerenciador_alunos.py, regra_de_negocio/gerenciador_ciclos.py, regra_de_negocio/gerenciador_notas.py, regra_de_negocio/gerenciador_turmas.py, regra_de_negocio/gerenciador_turmas_alunos.py, urls.py, views/funcoes_request_response.py
Passando o lint no código pois os prs estavam ficando muito grandes pra corrigir isso aqui
=> Passa lint sem alteração de funcionalidade

front/informacoes_turma.html
=> Ruth/Readequando valor  a zero#144

front/gerenciamento_aluno.html, front/scripts/gerenciamento_alunos.js, regra_de_negocio/gerenciador_alunos.py
Mudança de sexo para gênero e adição do upperCase
#143
=> mudança de sexo para genero

front/editar_turma.html
=> Ruth/Substituir termos Sprint por Ciclo #139

front/informacoes_turma.html, front/scripts/gerenciamento_turmas.js, front/scripts/informacoes_turmas.js, front/style/gerenciamento_turmas.css, front/style/informacoes_turma.css, regra_de_negocio/gerenciador_ciclos.py
Fix para:
- Edição de Ciclos
- Adição de data de Início
=> Compila as modificações de turmas após o revert

front/scripts/informacoes_turmas.js
=> Ruth/números _de _0 _a _10#171

dados/notas.json, front/scripts/informacoes_turmas.js, regra_de_negocio/gerenciador_notas.py
Listagem do fee resolvido!
#134
=> listar fee corrigido

front/scripts/informacoes_turmas.js
=> Ruth/notas positivas 0 a 10#171

regra_de_negocio/gerenciador_notas.py
Mudando para 2 casas decimais a média do FEE
=> Mudando para 2 casas decimais fee sara 

front/informacoes_turma.html, front/scripts/informacoes_turmas.js, front/style/informacoes_turma.css
#145
Para habilitar os campos de edição, a data de início da turma deve estar na janela de 5 dias ao final do ciclo.
exemplo: dia 20/10/2023 -> turma 1
Mudança das cores dos campos habilitados e desabilitados (vide figura).
Inclusão do cabeçalho na tabela de notas.
Modifica o layout da tabela de notas.
=> S 03 145 habilitar desabilitar notas

front/scripts/gerenciamento_turmas_criar.js
Tava dando um bug na hora de criar turma, que não era redirecionado para outra página e nem mostrava o alert quando dava certo. Pq como ainda tava dentro da promise nunca chegava nele, mesmo quando a promisse era comprida.
=> arruma bug na hora de criar turma

front/scripts/informacoes_turmas.js
#183 
- Todas as notas sao adicionadas a requisição para o back-end.
- Realizado validações:
- Verificar se algum valor foi alterado, para nao aparecer o alert.
- Adiciona apenas notas que foram alteradas ao corpo da requisição
```
const valor = parseFloat(nota.value); 
const valorOriginal = parseFloat(nota.dataset.ValorOriginal); 
if (isNaN(valor) || valor < 0 || valor > 10) {
// Se a nota não for um número ou estiver fora do intervalo, marca como inválida
notasInvalidas = true;
nota.classList.add("nota-invalida"); // Adiciona uma classe para destacar a nota inválida visualmente
}
// Verificar se o valor é estritamente diferente, para só sobreescrever uma nota diferente
if (valor !== valorOriginal) {
NenhumaNotaModificada = false;
requestBody[id_nota] = {
id_turma: id_turma,
id_aluno: …
```
=> [FIX] Apenas notas modificadas devem ser sobrescritas no banco

dados/turmas.json, front/scripts/gerenciamento_turmas.js, front/style/gerenciamento_turmas.css, regra_de_negocio/gerenciador_ciclos.py, urls.py, views/funcoes_request_response.py
Reverts ClaraSantosmf/FATEC-API-1-SEMESTRE#188
=> Revert "Debito/listar detalhes turmas"

front/gerenciamento_aluno.html
=> [Débito técnico] Scroll para selecionar opções de gênero

front/scripts/gerenciamento_alunos.js
issue #211 
- alterado o 'container' de editar aluno de form para div, impedindo duas ações simultâneas (o envio do form e a ação do botão de salvar).
- corrigido o problema com a exibição da data no input.
=> Corrige o bug com a data de nascimento do aluno. Issue #211

front/index.html, front/relatorio.html, front/scripts/relatorio.js, regra_de_negocio/service.py, urls.py, views/funcoes_request_response.py
#208 
Relatório dos gráficos obtidos de FEE x Aluno e FEE x Turma
=> Relatório dos gráficos obtidos de FEE x Aluno e FEE x Turma

dados/ciclos.json, devdb/ciclos.json, front/informacoes_turma.html, front/scripts/informacoes_turmas.js, front/style/informacoes_turma.css, regra_de_negocio/gerenciador_ciclos.py
- Adiciona nomes aos ciclos (ambos os json).
- Modifica a criação de turmas.
- Adiciona campos no front de edição de ciclos e altera a requisição de edição.
=> S 04 #221 renomear ciclos

dados/ciclos.json, front/informacoes_turma.html, front/style/informacoes_turma.css, regra_de_negocio/gerenciador_notas.py, regra_de_negocio/service.py
- Arumei a tela que mostra as notas dos alunos e limpei o codigo.
- A turma 1 estava com 5 ciclos mas os alunos só tinham 4 notas, então reestruturei o ciclos.json
=> S 04/main quarta sprint

front/scripts/relatorio.js, regra_de_negocio/gerenciador_turmas_alunos.py, views/funcoes_request_response.py
#238 #206
Correções devido à modificação no FEE.
=> Corrige o relatório de fee. #238
